name = "Goa"
license = "MIT"
licenselink = "https://github.com/kidager/hugo-goa/blob/master/LICENSE.md"
description = "Edited Simple Minimalist Hugo Theme"
homepage = "https://github.com/kidager/hugo-goa"
tags = ["Roboto", "Lato", "Roboto Slab", "bootstrap", "font awesome", "minimal", "clean"]
features = ["blog", "pages", "minimal", "responsive", "404", "icons", "disqus", "anlaytics"]
min_version = 0.17

[author]
  name = "Jacem Chaieb"
  homepage = "https://github.com/kidager"
